# Generated by Django 3.2.19 on 2023-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
